// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputModality } from "../InputModality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ModelAvailabilityNux } from "./ModelAvailabilityNux";
import type { ModelServiceTier } from "./ModelServiceTier";
import type { ModelUpgradeInfo } from "./ModelUpgradeInfo";
import type { ReasoningEffortOption } from "./ReasoningEffortOption";

export type Model = { id: string, model: string, upgrade: string | null, upgradeInfo: ModelUpgradeInfo | null, availabilityNux: ModelAvailabilityNux | null, displayName: string, description: string, hidden: boolean, supportedReasoningEfforts: Array<ReasoningEffortOption>,
/**
 * Legacy effective default retained for existing clients.
 */
defaultReasoningEffort: ReasoningEffort,
/**
 * Exact default advertised by the source model metadata.
 *
 * An authoritative manifest may intentionally omit a default even when it advertises supported efforts. Clients using manifest catalog semantics should prefer this field and omit an override when it is null.
 */
advertisedDefaultReasoningEffort: ReasoningEffort | null, inputModalities: Array<InputModality>, supportsPersonality: boolean,
/**
 * Deprecated: use `serviceTiers` instead.
 */
additionalSpeedTiers: Array<string>, serviceTiers: Array<ModelServiceTier>,
/**
 * Catalog default service tier id for this model, when one is configured.
 */
defaultServiceTier: string | null, isDefault: boolean, };
