// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Thread } from "./Thread";

export type ThreadStartedNotification = { thread: Thread,
/**
 * Whether the thread carries manifest-scoped provider lineage.
 *
 * This may remain true after switching back to an ordinary provider so
 * clients keep thread-scoped catalog behavior. Older app servers omit this
 * hint; clients should then preserve their existing provider-identification
 * fallback.
 */
modelProviderUsesManifest: boolean | null, };
